function skillsMember() {
  var skills = [
    'JavaScript',
    'React',
    'Angular',
    'Vue',
    'Node',
    'Express',
    'MongoDB',
    'SQL',
    'Python',
    'Django',
    'Flask',
    'CSS',
    'HTML',
    'Bootstrap',
    'SASS',
    'LESS',
    'jQuery',
    'Git',
    'GitHub',
    'GitLab',
    'Bitbucket',
    'JIRA',
    'Confluence',
    'Trello',
    'Slack',
    'Figma',
    'Sketch',
    'Photoshop',
    'Illustrator',
    'InDesign',
    'XD',
    'Zeplin',
    'InVision',
    'WordPress',
    'Shopify',
    'Magento',
    'Joomla',
    'Drupal',
    'Salesforce',
    'SAP',
    'Swift',
    'Objective-C',
    'Kotlin',
    'Java',
    'C#',
    'C++',
    'R',
    'Ruby',
    'Perl',
    'PHP',
    'Go',
    'Scala',
    'Rust',
    'Haskell',
    'Erlang',
    'Clojure',
    'Lua',
    'Dart',
    'Flutter',
    'TensorFlow',
    'PyTorch',
    'Keras',
    'Caffe',
    'Torch',
    'OpenCV',
    'Unity',
    'Unreal',
    'Blender',
    'Maya',
    '3ds Max',
    'AutoCAD',
    'Revit',
    'SolidWorks',
    'SketchUp',
    'Rhino',
    'Grasshopper',
    'Lumion',
    'V-Ray',
    'Corona',
    'Arnold',
    'Redshift',
    'Octane',
    'KeyShot',
    'After Effects',
    'Premiere',
    'Final Cut Pro',
    'DaVinci Resolve',
    'Avid',
    'Pro Tools',
    'Logic Pro',
    'Ableton Live',
    'FL Studio',
    'Cinema 4D',
    'ZBrush',
    'Substance Painter',
    'Substance Designer',
    'Mari',
    'Nuke',
    'Houdini',
    'Mudbox',
    'MotionBuilder',